import {createHash} from 'node:crypto';
import {mkdir,readFile,writeFile,rename,unlink,readdir,stat} from 'node:fs/promises';
import {readFileSync} from 'node:fs';
import path from 'node:path';
const hash=k=>createHash('sha256').update(k).digest('hex');
async function atomic(file,data){await mkdir(path.dirname(file),{recursive:true});const tmp=file+'.'+crypto.randomUUID()+'.tmp';await writeFile(tmp,data);await rename(tmp,file);}
export class KVNamespace {
 constructor(db,name){this.db=db;this.name=name;db.sqlite.exec('CREATE TABLE IF NOT EXISTS _kv(namespace TEXT,key TEXT,value TEXT,metadata TEXT,expires INTEGER,PRIMARY KEY(namespace,key))');}
 async get(key,type='text'){const r=this.db.sqlite.prepare('SELECT * FROM _kv WHERE namespace=? AND key=?').get(this.name,key);if(!r||(r.expires&&r.expires<=Date.now()/1000))return null;type=typeof type==='object'?type.type:type;return type==='json'?JSON.parse(r.value):type==='arrayBuffer'?Uint8Array.from(Buffer.from(r.value)).buffer:r.value;}
 async getWithMetadata(key,type='text'){const value=await this.get(key,type);const r=this.db.sqlite.prepare('SELECT metadata FROM _kv WHERE namespace=? AND key=?').get(this.name,key);return {value,metadata:value===null?null:r?.metadata?JSON.parse(r.metadata):null};}
 async put(key,value,options={}){const expires=options.expiration|| (options.expirationTtl?Math.floor(Date.now()/1000)+options.expirationTtl:null);this.db.sqlite.prepare('INSERT OR REPLACE INTO _kv VALUES (?,?,?,?,?)').run(this.name,key,String(value),options.metadata?JSON.stringify(options.metadata):null,expires);}
 async delete(key){this.db.sqlite.prepare('DELETE FROM _kv WHERE namespace=? AND key=?').run(this.name,key);}
 async list({prefix='',limit=1000,cursor=''}={}){const keys=this.db.sqlite.prepare('SELECT key AS name,metadata,expires AS expiration FROM _kv WHERE namespace=? AND key LIKE ? AND key>? AND (expires IS NULL OR expires>?) ORDER BY key LIMIT ?').all(this.name,prefix+'%',cursor,Date.now()/1000,limit+1);const more=keys.length>limit;const selected=keys.slice(0,limit).map(k=>({...k,metadata:k.metadata?JSON.parse(k.metadata):undefined}));return {keys:selected,list_complete:!more,cursor:more?selected.at(-1).name:''};}
}
export class Bucket {
 constructor(root){this.root=root;}
 file(key){return path.join(this.root,hash(key));}
 async put(key,value,options={}){let bytes;if(value?.getReader)bytes=Buffer.from(await new Response(value).arrayBuffer());else if(typeof value==='string')bytes=Buffer.from(value);else if(value?.arrayBuffer)bytes=Buffer.from(await value.arrayBuffer());else bytes=Buffer.from(value);const meta={key,size:bytes.length,etag:createHash('md5').update(bytes).digest('hex'),uploaded:new Date().toISOString(),httpMetadata:options.httpMetadata||{},customMetadata:options.customMetadata||{},checksumSha256:createHash('sha256').update(bytes).digest('base64')};await atomic(this.file(key)+'.bin',bytes);await atomic(this.file(key)+'.json',JSON.stringify(meta));return this.object(meta);}
 object(meta,bytes,range){return {...meta,uploaded:new Date(meta.uploaded),httpEtag:'"'+meta.etag+'"',checksums:{md5:Uint8Array.from(Buffer.from(meta.etag,'hex')).buffer,sha256:meta.checksumSha256?Uint8Array.from(Buffer.from(meta.checksumSha256,'base64')).buffer:undefined},range,...(bytes?{body:new Response(bytes).body}:{}),arrayBuffer:async()=>Uint8Array.from(bytes).buffer,text:async()=>bytes.toString(),json:async()=>JSON.parse(bytes.toString()),writeHttpMetadata:headers=>{const map={contentType:'content-type',contentEncoding:'content-encoding',contentDisposition:'content-disposition',cacheControl:'cache-control',contentLanguage:'content-language'};for(const[k,v]of Object.entries(meta.httpMetadata))if(map[k])headers.set(map[k],v);}};}
 async head(key){try{return this.object(JSON.parse(await readFile(this.file(key)+'.json','utf8')));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
 async get(key,options={}){const meta=await this.head(key);if(!meta)return null;if(options.onlyIf?.etagDoesNotMatch===meta.etag)return meta;let bytes=await readFile(this.file(key)+'.bin');let range;
  const r=options.range;if(r instanceof Headers&&r.get('range')?.startsWith('bytes=')){const m=/^bytes=(\d*)-(\d*)$/.exec(r.get('range'));let offset=0,length=bytes.length;if(m&&(m[1]||m[2])){offset=m[1]?Number(m[1]):Math.max(0,bytes.length-Number(m[2]));const end=m[1]?(m[2]?Math.min(Number(m[2]),bytes.length-1):bytes.length-1):bytes.length-1;if(offset<=end&&offset<bytes.length)length=end-offset+1;else offset=0;}range={offset,length};bytes=bytes.subarray(offset,offset+length);}else if(r&&!(r instanceof Headers)){const offset=r.offset??Math.max(0,bytes.length-(r.suffix??bytes.length));const length=r.length??bytes.length-offset;range={offset,length};bytes=bytes.subarray(offset,offset+length);}
 return this.object(meta,bytes,range);}
 async delete(keys){for(const key of [].concat(keys))for(const ext of ['.bin','.json'])try{await unlink(this.file(key)+ext);}catch(e){if(e.code!=='ENOENT')throw e;}}
 async list({prefix='',limit=1000,cursor=''}={}){await mkdir(this.root,{recursive:true});const all=[];for(const f of await readdir(this.root))if(f.endsWith('.json')){const m=JSON.parse(await readFile(path.join(this.root,f),'utf8'));if(m.key.startsWith(prefix)&&m.key>cursor)all.push(this.object(m));}all.sort((a,b)=>a.key.localeCompare(b.key));return {objects:all.slice(0,limit),truncated:all.length>limit,cursor:all.length>limit?all[limit-1].key:undefined,delimitedPrefixes:[]};}
}
const mime={'.html':'text/html; charset=utf-8','.json':'application/json','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.wasm':'application/wasm'};
export class Assets {
 constructor(root){this.root=path.resolve(root);this.spa=path.basename(this.root)==='www';}
 async fetch(request){const url=new URL(typeof request==='string'||request instanceof URL?request:request.url);let p;try{p=decodeURIComponent(url.pathname);}catch{return new Response('Bad path',{status:400});}let file=path.resolve(this.root,'.'+p);if(!file.startsWith(this.root+path.sep)&&file!==this.root)return new Response('Forbidden',{status:403});try{const st=await stat(file);if(st.isDirectory())file=path.join(file,'index.html');return new Response(await readFile(file),{headers:{'content-type':mime[path.extname(file)]||'application/octet-stream'}});}catch(e){if(e.code==='ENOENT'||e.code==='ENOTDIR'){if(this.spa&&!path.extname(file))try{return new Response(await readFile(path.join(this.root,'index.html')),{headers:{'content-type':'text/html; charset=utf-8'}});}catch{}return new Response('Not Found',{status:404});}throw e;}}
}
export function installCache(){const map=new Map();const cache={match:async req=>{const key=req.method+':'+req.url;const item=map.get(key);if(!item||item.expires<Date.now()){map.delete(key);return undefined;}return item.res.clone();},put:async(req,res)=>{const h=res.headers.get('cloudflare-cdn-cache-control')||res.headers.get('cache-control')||'';const ttl=Number(/max-age=(\d+)/.exec(h)?.[1]||60)*1000;if(map.size>=500)map.delete(map.keys().next().value);map.set(req.method+':'+req.url,{res:res.clone(),expires:Date.now()+ttl});},delete:async req=>map.delete(req.method+':'+req.url)};globalThis.caches={open:async()=>cache,default:cache};}
