// Ported from apps/notify/src/notification-types.ts; TypeScript types erased; native runtime imports.
var NotificationType = /* @__PURE__ */ ((NotificationType2) => {
  NotificationType2[NotificationType2["RelationshipChanged"] = 1] = "RelationshipChanged";
  NotificationType2[NotificationType2["MessageReceived"] = 2] = "MessageReceived";
  NotificationType2[NotificationType2["MessageDeleted"] = 3] = "MessageDeleted";
  NotificationType2[NotificationType2["PresenceHeartbeatResponse"] = 4] = "PresenceHeartbeatResponse";
  NotificationType2[NotificationType2["RefreshLogin"] = 5] = "RefreshLogin";
  NotificationType2[NotificationType2["Logout"] = 6] = "Logout";
  NotificationType2["SubscriptionUpdateProfile"] = "AccountUpdate";
  NotificationType2["SubscriptionUpdateSelfProfile"] = "SelfAccountUpdate";
  NotificationType2["SubscriptionUpdatePresence"] = "PresenceUpdate";
  NotificationType2["SubscriptionUpdateGameSession"] = "RoomInstanceUpdate";
  NotificationType2["SubscriptionUpdateRoom"] = "RoomUpdate";
  NotificationType2[NotificationType2["SubscriptionUpdateRoomPlaylist"] = 16] = "SubscriptionUpdateRoomPlaylist";
  NotificationType2[NotificationType2["ModerationQuitGame"] = 20] = "ModerationQuitGame";
  NotificationType2[NotificationType2["ModerationUpdateRequired"] = 21] = "ModerationUpdateRequired";
  NotificationType2[NotificationType2["ModerationKick"] = 22] = "ModerationKick";
  NotificationType2[NotificationType2["ModerationKickAttemptFailed"] = 23] = "ModerationKickAttemptFailed";
  NotificationType2["ModerationRoomBan"] = "ModerationRoomBan";
  NotificationType2[NotificationType2["ServerMaintenance"] = 25] = "ServerMaintenance";
  NotificationType2[NotificationType2["GiftPackageReceived"] = 30] = "GiftPackageReceived";
  NotificationType2[NotificationType2["GiftPackageReceivedImmediate"] = 31] = "GiftPackageReceivedImmediate";
  NotificationType2[NotificationType2["GiftPackageRewardSelectionReceived"] = 32] = "GiftPackageRewardSelectionReceived";
  NotificationType2["PlayerProgressionLevelUpdate"] = "PlayerProgressionLevelUpdate";
  NotificationType2[NotificationType2["ProfileJuniorStatusUpdate"] = 40] = "ProfileJuniorStatusUpdate";
  NotificationType2[NotificationType2["RelationshipsInvalid"] = 50] = "RelationshipsInvalid";
  NotificationType2[NotificationType2["StorefrontBalanceAdd"] = 60] = "StorefrontBalanceAdd";
  NotificationType2[NotificationType2["StorefrontBalanceUpdate"] = 61] = "StorefrontBalanceUpdate";
  NotificationType2[NotificationType2["StorefrontBalancePurchase"] = 62] = "StorefrontBalancePurchase";
  NotificationType2[NotificationType2["ConsumableMappingAdded"] = 70] = "ConsumableMappingAdded";
  NotificationType2[NotificationType2["ConsumableMappingRemoved"] = 71] = "ConsumableMappingRemoved";
  NotificationType2[NotificationType2["PlayerEventCreated"] = 80] = "PlayerEventCreated";
  NotificationType2[NotificationType2["PlayerEventUpdated"] = 81] = "PlayerEventUpdated";
  NotificationType2[NotificationType2["PlayerEventDeleted"] = 82] = "PlayerEventDeleted";
  NotificationType2[NotificationType2["PlayerEventResponseChanged"] = 83] = "PlayerEventResponseChanged";
  NotificationType2[NotificationType2["PlayerEventResponseDeleted"] = 84] = "PlayerEventResponseDeleted";
  NotificationType2[NotificationType2["PlayerEventStateChanged"] = 85] = "PlayerEventStateChanged";
  NotificationType2["ChatMessageReceived"] = "ChatMessageReceived";
  NotificationType2["CommunityBoardUpdate"] = "CommunityBoardUpdate";
  NotificationType2[NotificationType2["CommunityBoardAnnouncementUpdate"] = 96] = "CommunityBoardAnnouncementUpdate";
  NotificationType2[NotificationType2["InventionModerationStateChanged"] = 100] = "InventionModerationStateChanged";
  NotificationType2[NotificationType2["FreeGiftButtonItemsAdded"] = 110] = "FreeGiftButtonItemsAdded";
  NotificationType2[NotificationType2["LocalRoomKeyCreated"] = 120] = "LocalRoomKeyCreated";
  NotificationType2[NotificationType2["LocalRoomKeyDeleted"] = 121] = "LocalRoomKeyDeleted";
  NotificationType2["AppVersionUpdate"] = "AppVersionUpdate";
  NotificationType2["AnnouncementUpdate"] = "AnnouncementUpdate";
  NotificationType2["AnnouncementDelete"] = "AnnouncementDelete";
  NotificationType2["ClubMembershipUpdate"] = "ClubMembershipUpdate";
  NotificationType2["CreatorClubSubscriptionUpdate"] = "CreatorClubSubscriptionUpdate";
  NotificationType2["CommerceSubscriptionUpdate"] = "CommerceSubscriptionUpdate";
  NotificationType2["GameConfigRefresh"] = "GameConfig.Refresh";
  NotificationType2["PlayerSettingsRefresh"] = "PlayerSettings.Refresh";
  NotificationType2["GoToFailure"] = "GoToFailure";
  NotificationType2["IncentivizedReferralUpdate"] = "IncentivizedReferralUpdate";
  NotificationType2["InfluencerSupportedUpdate"] = "InfluencerSupportedUpdate";
  NotificationType2["KeepsakeInstanceAdded"] = "KeepsakeInstanceAdded";
  NotificationType2["KeepsakeInstanceRemoved"] = "KeepsakeInstanceRemoved";
  NotificationType2["ModerationUnkick"] = "ModerationUnkick";
  NotificationType2["PhotonAccessToken"] = "PhotonAccessToken";
  NotificationType2["PlayerCustomAvatarItemModerated"] = "PlayerCustomAvatarItemModerated";
  NotificationType2["PlayerLeftChat"] = "PlayerLeftChat";
  NotificationType2["ProgressionEventsRecordUpdate"] = "ProgressionEventsRecordUpdate";
  NotificationType2["ReputationUpdate"] = "ReputationUpdate";
  NotificationType2["RewardSelectionReceived"] = "RewardSelectionReceived";
  NotificationType2["RoomCommentDeleted"] = "RoomCommentDeleted";
  NotificationType2["RoomCurrencyCreated"] = "RoomCurrencyCreated";
  NotificationType2["RoomCurrencyModified"] = "RoomCurrencyModified";
  NotificationType2["RoomCurrencyDeleted"] = "RoomCurrencyDeleted";
  NotificationType2["StringAutoLocalizationJob"] = "StringAutoLocalizationJob";
  NotificationType2["WebsiteInventionPurchase"] = "WebsiteInventionPurchase";
  NotificationType2["GiftManualConsumed"] = "gift.manualconsumed";
  NotificationType2["PushToDevice"] = "rrs.pushtodevice";
  return NotificationType2;
})(NotificationType || {});
export {
  NotificationType
};
